name: Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          tool-versions: .tool-versions

      - name: Test the code
        run: |
          # Run the test and capture the output
          output=$(scarb test)

          # Echo the entire output (optional, for debugging purposes)
          echo "$output"

          # Filter and echo the specific part of the output you are interested in
          echo "$output" | grep -E "Error: test result: FAILED. [0-9]+ passed; [0-9]+ failed; [0-9]+ ignored"
